

services:
  flutter_web:
    build: ./flutter_frontend
    ports:
      - "5555:5555"
    volumes:
      - ./flutter_frontend:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=5555

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./backend:/app
    working_dir: /app
    command: node index.js
