

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  flutter_web:
    build: ./flutter_frontend
    ports:
      - "5555:5555"
    volumes:
      - ./flutter_frontend:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=5555

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./backend:/app
    working_dir: /app
    command: node index.js
